import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getDatabase, ref, get, set, update, onValue, onDisconnect } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
import * as pdfjsLib from "https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs";
import { firebaseConfig, isFirebaseConfigured } from "./firebase-config.js";

pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs";

const $ = id => document.getElementById(id);
const setupView = $("setupView"), teacherView = $("teacherView"), studentView = $("studentView"), configView = $("configView"), toastEl = $("toast");
let auth, db, currentUser, currentMode="blind", drafts=[], roomCode="", roomData=null, roomUnsub=null, role=null, joinedNickname="", rankingDraft=[], resultTab="class", busy=false;
const MUSIC_HOSTS=["youtube.com","youtu.be","spotify.com","soundcloud.com","vimeo.com","bandcamp.com","deezer.com","music.apple.com","tidal.com"];

function toast(message,ms=2500){toastEl.textContent=message;toastEl.style.display="block";clearTimeout(toastEl._t);toastEl._t=setTimeout(()=>toastEl.style.display="none",ms)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function showOnly(which){setupView.classList.toggle("hidden",which!=="setup");teacherView.classList.toggle("hidden",which!=="teacher");studentView.classList.toggle("hidden",which!=="student");configView.classList.toggle("hidden",which!=="config")}
function normalizeCode(v){return String(v||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6)}
function modeLabel(m){return m==="tier"?"Tier List":m==="blind"?"Blind Ranking":"Ranking"}
function tracksArray(room=roomData){return room?.tracks?Object.values(room.tracks).sort((a,b)=>(a.order??0)-(b.order??0)):[]}
function participantsArray(){return roomData?.participants?Object.entries(roomData.participants).map(([uid,p])=>({uid,...p})).sort((a,b)=>String(a.nickname).localeCompare(String(b.nickname),"it")):[]}
function currentTrack(){return tracksArray()[roomData?.currentIndex||0]||null}
function makeCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let out="";for(let i=0;i<6;i++)out+=chars[Math.floor(Math.random()*chars.length)];return out}
async function uniqueCode(){for(let i=0;i<8;i++){const code=makeCode();if(!(await get(ref(db,`rooms/${code}`))).exists())return code}throw new Error("Impossibile creare il codice stanza")}

function youtubeId(url){if(!url)return"";try{const u=new URL(url);if(u.hostname.includes("youtu.be"))return u.pathname.replace("/","");if(u.searchParams.get("v"))return u.searchParams.get("v")}catch{}const m=String(url).match(/(?:v=|youtu\.be\/|embed\/)([A-Za-z0-9_-]{6,})/);return m?m[1]:""}
function trackImage(t){if(!t)return"";if(t.imageMethod==="upload")return t.imageData||"";if(t.imageMethod==="url")return t.imageUrl||"";if(t.imageMethod==="youtube"){const id=youtubeId(t.link);return id?`https://img.youtube.com/vi/${id}/hqdefault.jpg`:""}return""}
function coverHtml(t,show=true){const src=show?trackImage(t):"";return src?`<img class="stage-image" src="${esc(src)}" alt="">`:`<div class="stage-placeholder">🎼</div>`}

/* SETUP */
document.querySelectorAll(".mode-card").forEach(btn=>btn.addEventListener("click",()=>{currentMode=btn.dataset.mode;document.querySelectorAll(".mode-card").forEach(x=>x.classList.toggle("active",x===btn))}));
$("addTrackBtn").addEventListener("click",()=>{drafts.push({title:"",link:"",imageMethod:"none",imageUrl:"",imageData:""});renderDrafts()});
$("pdfInput").addEventListener("change",async e=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;try{$("setupHint").textContent="Sto leggendo il PDF e cercando i link…";const found=await extractTracksFromPdf(f);if(!found.length){toast("Non ho trovato link cliccabili nel PDF");$("setupHint").textContent="";return}drafts=found.map(x=>({...x,imageMethod:"none",imageUrl:"",imageData:""}));renderDrafts();$("setupHint").textContent=`${found.length} ascolti importati. Controlla i titoli.`}catch(err){console.error(err);toast("Non riesco a leggere questo PDF");$("setupHint").textContent=""}});

function renderDrafts(){const ed=$("trackEditor");$("emptyTracks").classList.toggle("hidden",drafts.length>0);ed.innerHTML=drafts.map((t,i)=>{const p=draftImage(t);return`<article class="track-card"><div class="track-head"><div class="track-head-left"><span class="track-index">${i+1}</span><span>Ascolto ${i+1}</span></div><button class="button danger" data-remove="${i}">Elimina</button></div><div class="track-grid"><div><label>Titolo</label><input data-field="title" data-index="${i}" value="${esc(t.title)}" placeholder="Titolo dell'ascolto"></div><div><label>Link ascolto</label><input data-field="link" data-index="${i}" value="${esc(t.link)}" placeholder="YouTube, Spotify, Vimeo…"></div><div><label>Immagine</label><div class="image-row">${p?`<img class="preview" src="${esc(p)}" alt="">`:`<div class="preview-placeholder">🎼</div>`}<div><select data-field="imageMethod" data-index="${i}"><option value="none" ${t.imageMethod==="none"?"selected":""}>Nessuna immagine</option><option value="upload" ${t.imageMethod==="upload"?"selected":""}>Carica dal PC / tablet</option><option value="url" ${t.imageMethod==="url"?"selected":""}>Inserisci URL immagine</option><option value="youtube" ${t.imageMethod==="youtube"?"selected":""}>Miniatura YouTube</option></select>${t.imageMethod==="upload"?`<label class="file-mini">📁 Scegli immagine<input type="file" accept="image/*" data-upload="${i}"></label>`:""}${t.imageMethod==="url"?`<input style="margin-top:7px" data-field="imageUrl" data-index="${i}" value="${esc(t.imageUrl)}" placeholder="https://…">`:""}</div></div></div></div></article>`}).join("");
  ed.querySelectorAll("[data-remove]").forEach(b=>b.addEventListener("click",()=>{drafts.splice(Number(b.dataset.remove),1);renderDrafts()}));
  ed.querySelectorAll("[data-field]").forEach(inp=>inp.addEventListener(inp.tagName==="SELECT"?"change":"input",()=>{const i=Number(inp.dataset.index),f=inp.dataset.field;drafts[i][f]=inp.value;if(f==="imageMethod"){if(inp.value!=="upload")drafts[i].imageData="";renderDrafts()}else if(f==="link"||f==="imageUrl"){clearTimeout(inp._r);inp._r=setTimeout(renderDrafts,400)}}));
  ed.querySelectorAll("[data-upload]").forEach(inp=>inp.addEventListener("change",async()=>{const f=inp.files?.[0];if(!f)return;drafts[Number(inp.dataset.upload)].imageData=await resizeImage(f);drafts[Number(inp.dataset.upload)].imageMethod="upload";renderDrafts()}));
}
function draftImage(t){if(t.imageMethod==="upload")return t.imageData||"";if(t.imageMethod==="url")return t.imageUrl||"";if(t.imageMethod==="youtube"){const id=youtubeId(t.link);return id?`https://img.youtube.com/vi/${id}/hqdefault.jpg`:""}return""}
function resizeImage(file,max=300,q=.56){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const im=new Image();im.onerror=reject;im.onload=()=>{const s=Math.min(1,max/Math.max(im.width,im.height)),w=Math.round(im.width*s),h=Math.round(im.height*s),c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(im,0,0,w,h);resolve(c.toDataURL("image/jpeg",q))};im.src=r.result};r.readAsDataURL(file)})}

/* PDF */
async function extractTracksFromPdf(file){const bytes=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjsLib.getDocument({data:bytes}).promise,all=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),[ann,text]=await Promise.all([page.getAnnotations(),page.getTextContent()]),lines=buildLines(text.items);for(const a of ann){const url=a.url||a.unsafeUrl||"";if(!/^https?:\/\//i.test(url))continue;const r=a.rect||[0,0,0,0],y=(Number(r[1])+Number(r[3]))/2;all.push({title:nearestTitle(lines,y,url),link:url})}}const seen=new Set(),uniq=all.filter(x=>!seen.has(x.link)&&seen.add(x.link)),music=uniq.filter(x=>isMusicUrl(x.link)),chosen=music.length?music:uniq;return chosen.map((x,i)=>({title:sanitizeTitle(x.title)||`Ascolto ${i+1}`,link:x.link}))}
function buildLines(items){const rows=[];for(const it of items){const str=String(it.str||"").trim();if(!str)continue;const x=Number(it.transform?.[4]||0),y=Number(it.transform?.[5]||0);let row=rows.find(r=>Math.abs(r.y-y)<3);if(!row){row={y,parts:[]};rows.push(row)}row.parts.push({x,str})}return rows.map(r=>({y:r.y,text:r.parts.sort((a,b)=>a.x-b.x).map(p=>p.str).join(" ").replace(/\s+/g," ").trim()}))}
function nearestTitle(lines,y,url){for(const line of [...lines].sort((a,b)=>Math.abs(a.y-y)-Math.abs(b.y-y)).slice(0,5)){const t=sanitizeTitle(line.text);if(t&&!t.includes(url)&&t.length>=3)return t}return""}
function sanitizeTitle(t){let s=String(t||"").replace(/https?:\/\/\S+/gi,"").replace(/\u200b/g,"").replace(/\s+/g," ").trim();return s.length>100?s.slice(0,97)+"…":s}
function isMusicUrl(url){try{const h=new URL(url).hostname.toLowerCase().replace(/^www\./,"");return MUSIC_HOSTS.some(x=>h===x||h.endsWith("."+x))}catch{return false}}

/* CREATE / JOIN */
$("createSessionBtn").addEventListener("click",async()=>{if(!db||busy)return;const valid=drafts.map((t,i)=>({...t,title:String(t.title||"").trim(),link:String(t.link||"").trim(),order:i})).filter(t=>t.title);if(valid.length<2)return toast("Inserisci almeno 2 ascolti");if(valid.length>12)return toast("Per ora usa al massimo 12 ascolti");busy=true;$("createSessionBtn").disabled=true;try{const code=await uniqueCode(),tracks={};valid.forEach((t,i)=>tracks[`t${i+1}`]={id:`t${i+1}`,order:i,title:t.title,link:t.link,imageMethod:t.imageMethod||"none",imageUrl:t.imageMethod==="url"?(t.imageUrl||""):"",imageData:t.imageMethod==="upload"?(t.imageData||""):""});await set(ref(db,`rooms/${code}`),{ownerUid:currentUser.uid,title:String($("sessionTitle").value||"Music Ranking Live").trim(),mode:currentMode,phase:"lobby",currentIndex:0,revealed:false,createdAt:Date.now(),options:{showTitle:$("showTitle").checked,showImage:$("showImage").checked},tracks});role="teacher";roomCode=code;subscribeRoom(code);showOnly("teacher")}catch(e){console.error(e);toast(e.message||"Non riesco a creare la sessione")}finally{busy=false;$("createSessionBtn").disabled=false}});
$("joinBtn").addEventListener("click",joinRoom);
async function joinRoom(){if(!db||busy)return;const q=new URLSearchParams(location.search).get("room"),code=normalizeCode(q||$("joinCode").value),nick=String($("nickname").value||"").trim().slice(0,30);if(code.length<4)return toast("Inserisci il codice stanza");if(!nick)return toast("Inserisci un nickname");busy=true;$("joinBtn").disabled=true;try{const snap=await get(ref(db,`rooms/${code}`));if(!snap.exists())throw new Error("Stanza non trovata");roomCode=code;role="student";joinedNickname=nick;const pr=ref(db,`rooms/${code}/participants/${currentUser.uid}`);await set(pr,{nickname:nick,joinedAt:Date.now()});try{await onDisconnect(pr).remove()}catch{}subscribeRoom(code);showOnly("student")}catch(e){console.error(e);toast(e.message||"Non riesco a entrare")}finally{busy=false;$("joinBtn").disabled=false}}
function subscribeRoom(code){if(roomUnsub)roomUnsub();roomUnsub=onValue(ref(db,`rooms/${code}`),snap=>{if(!snap.exists()){toast("La stanza non è più disponibile");return}roomData=snap.val();role==="teacher"?renderTeacher():renderStudent()})}

/* TEACHER */
function renderTeacher(){const t=currentTrack(),people=participantsArray();teacherView.innerHTML=`<div class="teacher-layout"><section class="panel"><div class="badges"><span class="badge">🎵 ${esc(modeLabel(roomData.mode))}</span><span class="badge">👥 ${people.length} studenti</span>${roomData.phase==="voting"||roomData.phase==="ranking"?`<span class="badge">✅ ${getResponseCount()} risposte</span>`:""}</div><h2>${esc(roomData.title)}</h2><div class="room-code-box"><span>STANZA</span><strong>${esc(roomCode)}</strong></div><div class="section-title" style="margin-top:15px"><h2>Partecipanti</h2></div><div class="participant-list">${people.length?people.map(p=>`<span class="participant-chip">👤 ${esc(p.nickname)}</span>`).join(""):`<span class="hint">In attesa degli studenti…</span>`}</div><hr style="border:0;border-top:1px solid #e7d8ef;margin:17px 0">${teacherStage(t)}<div class="action-row">${teacherButtons(t)}<button id="resetRoomBtn" class="button danger">Reset</button></div></section><aside class="panel panel-dark qr-wrap"><div class="instrument-strip" style="justify-content:center;margin-bottom:10px"><span>🎻</span><span>🎹</span><span>🎺</span></div><h2>Scansiona e vota</h2><div id="qrCode"></div><p class="hint light">Gli studenti vedono solo stanza e nickname.</p></aside></div>`;renderQr();bindTeacher(t)}
function teacherStage(t){const total=tracksArray().length;if(roomData.phase==="lobby")return`<div class="hero-stage"><div class="stage-placeholder">🎧</div><div><div class="listen-label">READY?</div><div class="stage-title">Accendiamo la musica!</div></div></div>`;if(roomData.phase==="listening"||roomData.phase==="voting")return`<div class="hero-stage"><div>${coverHtml(t,true)}</div><div><div class="listen-label">ASCOLTO ${(roomData.currentIndex||0)+1} / ${total}</div><div class="stage-title">${esc(t?.title||"")}</div><div class="mini-instruments"><span>🎻</span><span>🎹</span><span>🎺</span><span>🥁</span><span>🎷</span><span>🎸</span></div></div></div>`;if(roomData.phase==="ranking")return`<div class="hero-stage"><div class="stage-placeholder">🏆</div><div><div class="listen-label">ULTIMO ROUND</div><div class="stage-title">Ora classifica!</div></div></div>`;if(roomData.phase==="ready")return`<div class="hero-stage"><div class="stage-placeholder">✨</div><div><div class="listen-label">FINE VOTAZIONI</div><div class="stage-title">Pronti al reveal?</div></div></div>`;if(roomData.phase==="results")return classResultsHtml();return""}
function teacherButtons(t){const last=(roomData.currentIndex||0)>=tracksArray().length-1;if(roomData.phase==="lobby")return`<button id="startBtn" class="button primary">▶️ Avvia ASCOLTO 1</button>`;if(roomData.phase==="listening"||roomData.phase==="voting"){const open=t?.link?`<button id="openTrackBtn" class="button dark">🔗 Apri ascolto</button>`:"",label=roomData.mode==="ranking"?(last?"🏆 Apri classifica finale":"➡️ Prossimo ascolto"):(last?"✅ Chiudi votazioni":"➡️ Prossimo ascolto");return`${open}<button id="nextBtn" class="button primary">${label}</button>`}if(roomData.phase==="ranking"||roomData.phase==="ready")return`<button id="revealBtn" class="button primary">🏆 Rivela risultati</button>`;if(roomData.phase==="results")return`<button id="newRoundBtn" class="button secondary">↻ Nuova partita</button>`;return""}
function bindTeacher(t){$("startBtn")?.addEventListener("click",()=>update(ref(db,`rooms/${roomCode}`),{phase:roomData.mode==="ranking"?"listening":"voting",currentIndex:0,revealed:false}));$("openTrackBtn")?.addEventListener("click",()=>t?.link&&window.open(t.link,"_blank","noopener"));$("nextBtn")?.addEventListener("click",async()=>{const last=(roomData.currentIndex||0)>=tracksArray().length-1;if(roomData.mode==="ranking"){if(last)await update(ref(db,`rooms/${roomCode}`),{phase:"ranking"});else await update(ref(db,`rooms/${roomCode}`),{currentIndex:(roomData.currentIndex||0)+1})}else{if(last)await update(ref(db,`rooms/${roomCode}`),{phase:"ready"});else await update(ref(db,`rooms/${roomCode}`),{currentIndex:(roomData.currentIndex||0)+1})}});$("revealBtn")?.addEventListener("click",()=>update(ref(db,`rooms/${roomCode}`),{phase:"results",revealed:true}));const reset=()=>update(ref(db,`rooms/${roomCode}`),{phase:"lobby",currentIndex:0,revealed:false,tierVotes:null,blindVotes:null,rankings:null});$("resetRoomBtn")?.addEventListener("click",reset);$("newRoundBtn")?.addEventListener("click",reset)}
function getResponseCount(){const t=currentTrack();if(!t)return 0;if(roomData.mode==="tier")return Object.keys(roomData.tierVotes?.[t.id]||{}).length;if(roomData.mode==="blind")return Object.values(roomData.blindVotes||{}).filter(v=>Object.values(v||{}).includes(t.id)).length;if(roomData.mode==="ranking"&&roomData.phase==="ranking")return Object.keys(roomData.rankings||{}).length;return 0}
function renderQr(){const el=$("qrCode");if(!el||typeof QRCode==="undefined")return;el.innerHTML="";const base=location.href.split("?")[0].split("#")[0];new QRCode(el,{text:`${base}?room=${encodeURIComponent(roomCode)}`,width:190,height:190})}

/* STUDENT */
function renderStudent(){const ts=tracksArray(),t=currentTrack();studentView.innerHTML=`<section class="panel panel-dark"><div class="badges"><span class="badge">👤 ${esc(joinedNickname)}</span><span class="badge">🎵 ${esc(modeLabel(roomData.mode))}</span><span class="badge">Stanza ${esc(roomCode)}</span></div>${studentContent(t,ts)}</section>`;bindStudent(t,ts)}
function studentStage(t){return`<div class="hero-stage"><div>${coverHtml(t,roomData.options?.showImage!==false)}</div><div><div class="listen-label">ASCOLTO ${(roomData.currentIndex||0)+1} / ${tracksArray().length}</div><div class="stage-title">${esc(roomData.options?.showTitle===false?`Ascolto ${(roomData.currentIndex||0)+1}`:(t?.title||""))}</div><div class="mini-instruments"><span>🎻</span><span>🎹</span><span>🥁</span><span>🎸</span></div></div></div>`}
function studentContent(t,ts){if(roomData.phase==="lobby")return`<div class="hero-stage"><div class="stage-placeholder">🎧</div><div><div class="listen-label">SEI DENTRO</div><div class="stage-title">Aspetta il primo ascolto</div></div></div>`;if(roomData.phase==="listening")return studentStage(t);if(roomData.phase==="voting"){if(roomData.mode==="tier")return tierVoteHtml(t);if(roomData.mode==="blind")return blindVoteHtml(t,ts)}if(roomData.phase==="ranking")return rankingVoteHtml(ts);if(roomData.phase==="ready")return`<div class="hero-stage"><div class="stage-placeholder">✅</div><div><div class="listen-label">FATTO</div><div class="stage-title">Voto registrato</div></div></div>`;if(roomData.phase==="results")return studentResultsHtml();return`<p>Attendi…</p>`}
function tierVoteHtml(t){const mine=roomData.tierVotes?.[t.id]?.[currentUser.uid]||"";const defs=[["S","🔥","PAZZESCA"],["A","🎧","PLAYLIST"],["B","👍","MI PIACE"],["C","😐","COSÌ COSÌ"],["D","👎","NON FA PER ME"]];return`${studentStage(t)}<p><strong>Che voto gli dai?</strong></p><div class="tier-grid">${defs.map(([x,e,n])=>`<button class="tier-button tier-${x} ${mine===x?"selected":""}" data-tier="${x}"><span class="tier-letter">${e} ${x}</span><span class="tier-name">${n}</span></button>`).join("")}</div>`}
function blindVoteHtml(t,ts){const votes=roomData.blindVotes?.[currentUser.uid]||{},entries=Object.entries(votes),existing=entries.find(([,id])=>id===t.id),occupied=new Set(entries.map(([p])=>String(p))),buttons=ts.map((_,i)=>`<button class="position-button" data-position="${i+1}" ${occupied.has(String(i+1))?"disabled":""}>${i+1}</button>`).join(""),slots=ts.map((_,i)=>{const pos=String(i+1),id=votes[pos],f=ts.find(x=>x.id===id);return`<div class="slot"><span class="slot-number">${pos}</span><span>${f?esc(f.title):`<span class="hint light">posto libero</span>`}</span></div>`}).join("");return`${studentStage(t)}${existing?`<p><strong>🔒 Hai scelto il posto ${esc(existing[0])}.</strong></p>`:`<p><strong>Dove lo metti?</strong> Una volta scelto, il posto si blocca.</p><div class="positions">${buttons}</div>`}<div class="slots">${slots}</div>`}
function rankingVoteHtml(ts){if(!rankingDraft.length||rankingDraft.length!==ts.length)rankingDraft=ts.map(t=>t.id);const map=Object.fromEntries(ts.map(t=>[t.id,t.title]));return`<div class="hero-stage"><div class="stage-placeholder">🏆</div><div><div class="listen-label">TOP LIST</div><div class="stage-title">Crea la tua classifica</div></div></div><div class="ranking-list">${rankingDraft.map((id,i)=>`<div class="rank-row"><span class="rank-number">${i+1}</span><span>${esc(map[id]||id)}</span><span class="move-buttons"><button data-move="${i}" data-dir="-1" ${i===0?"disabled":""}>↑</button><button data-move="${i}" data-dir="1" ${i===rankingDraft.length-1?"disabled":""}>↓</button></span></div>`).join("")}</div><button id="saveRankingBtn" class="button primary wide">Conferma classifica</button>`}
function bindStudent(t,ts){document.querySelectorAll("[data-tier]").forEach(b=>b.addEventListener("click",()=>set(ref(db,`rooms/${roomCode}/tierVotes/${t.id}/${currentUser.uid}`),b.dataset.tier)));document.querySelectorAll("[data-position]").forEach(b=>b.addEventListener("click",async()=>{if(busy)return;busy=true;try{const votes=roomData.blindVotes?.[currentUser.uid]||{};if(Object.values(votes).includes(t.id))return toast("Hai già posizionato questo ascolto");await set(ref(db,`rooms/${roomCode}/blindVotes/${currentUser.uid}/${b.dataset.position}`),t.id)}catch(e){toast("Questa posizione non è più disponibile")}finally{busy=false}}));document.querySelectorAll("[data-move]").forEach(b=>b.addEventListener("click",()=>{const i=Number(b.dataset.move),j=i+Number(b.dataset.dir);if(j<0||j>=rankingDraft.length)return;[rankingDraft[i],rankingDraft[j]]=[rankingDraft[j],rankingDraft[i]];renderStudent()}));$("saveRankingBtn")?.addEventListener("click",async()=>{await set(ref(db,`rooms/${roomCode}/rankings/${currentUser.uid}`),rankingDraft);toast("Classifica salvata!")});document.querySelectorAll("[data-result-tab]").forEach(b=>b.addEventListener("click",()=>{resultTab=b.dataset.resultTab;renderStudent()}))}

/* RESULTS */
function classTier(){const pts={S:5,A:4,B:3,C:2,D:1},lanes={S:[],A:[],B:[],C:[],D:[]};for(const t of tracksArray()){const votes=Object.values(roomData.tierVotes?.[t.id]||{}),avg=votes.length?votes.reduce((s,x)=>s+pts[x],0)/votes.length:0;let tier="D";if(avg>=4.5)tier="S";else if(avg>=3.5)tier="A";else if(avg>=2.5)tier="B";else if(avg>=1.5)tier="C";lanes[tier].push({title:t.title,avg})}return lanes}
function personalTier(){const lanes={S:[],A:[],B:[],C:[],D:[]};for(const t of tracksArray()){const tier=roomData.tierVotes?.[t.id]?.[currentUser.uid];if(tier&&lanes[tier])lanes[tier].push({title:t.title})}return lanes}
function tierLanes(lanes,avg=false){const labels={S:["🔥 S","PAZZESCA"],A:["🎧 A","PLAYLIST"],B:["👍 B","MI PIACE"],C:["😐 C","COSÌ COSÌ"],D:["👎 D","NON FA PER ME"]};return["S","A","B","C","D"].map(x=>`<div class="tier-lane"><div class="tier-lane-label tier-${x}"><strong>${labels[x][0]}</strong><span>${labels[x][1]}</span></div><div class="tier-lane-items">${lanes[x].length?lanes[x].map(v=>`<span class="result-chip">${esc(v.title)}${avg&&Number.isFinite(v.avg)?` <small>(${v.avg.toFixed(1)})</small>`:""}</span>`).join(""):`<span class="hint">—</span>`}</div></div>`).join("")}
function classRanking(){const ts=tracksArray(),pos=Object.fromEntries(ts.map(t=>[t.id,[]]));if(roomData.mode==="blind"){for(const votes of Object.values(roomData.blindVotes||{}))for(const [p,id] of Object.entries(votes||{}))if(pos[id])pos[id].push(Number(p))}else{for(const order of Object.values(roomData.rankings||{}))if(Array.isArray(order))order.forEach((id,i)=>pos[id]?.push(i+1))}return ts.map(t=>{const a=pos[t.id],v=a.length?a.reduce((x,y)=>x+y,0)/a.length:999;return{title:t.title,avg:v}}).sort((a,b)=>a.avg-b.avg)}
function rankingTable(items){return`<table class="results-table"><thead><tr><th>#</th><th>Ascolto</th><th>Posizione media</th></tr></thead><tbody>${items.map((x,i)=>`<tr><td>${i===0?"🥇":i===1?"🥈":i===2?"🥉":i+1}</td><td>${esc(x.title)}</td><td>${x.avg===999?"—":x.avg.toFixed(2)}</td></tr>`).join("")}</tbody></table>`}
function personalRanking(){const ts=tracksArray(),map=Object.fromEntries(ts.map(t=>[t.id,t.title]));let ordered=[];if(roomData.mode==="blind"){const votes=roomData.blindVotes?.[currentUser.uid]||{};ordered=Object.entries(votes).map(([p,id])=>({p:Number(p),id})).sort((a,b)=>a.p-b.p)}else{const o=roomData.rankings?.[currentUser.uid]||[];ordered=Array.isArray(o)?o.map((id,i)=>({p:i+1,id})):[]}return`<div class="slots">${ordered.length?ordered.map(x=>`<div class="slot"><span class="slot-number">${x.p}</span><span>${esc(map[x.id]||x.id)}</span></div>`).join(""):`<p class="hint light">Nessuna classifica personale salvata.</p>`}</div>`}
function classResultsHtml(){return roomData.mode==="tier"?`<h2>🏆 Tier List della classe</h2>${tierLanes(classTier(),true)}`:`<h2>🏆 Classifica della classe</h2>${rankingTable(classRanking())}`}
function studentResultsHtml(){const sw=`<div class="switcher"><button data-result-tab="mine" class="${resultTab==="mine"?"active":""}">👤 La mia</button><button data-result-tab="class" class="${resultTab==="class"?"active":""}">👥 Classe</button></div>`;if(roomData.mode==="tier")return`<h2>🏆 Risultati finali</h2>${sw}${resultTab==="mine"?tierLanes(personalTier(),false):tierLanes(classTier(),true)}`;return`<h2>🏆 Risultati finali</h2>${sw}${resultTab==="mine"?personalRanking():rankingTable(classRanking())}`}

/* INIT */
async function init(){const q=normalizeCode(new URLSearchParams(location.search).get("room"));if(q){$("joinCode").value=q;$("qrRoomCode").textContent=q;$("qrRoomBanner").classList.remove("hidden");$("manualRoomField").classList.add("hidden");setTimeout(()=>$("nickname").focus(),50)}renderDrafts();if(!isFirebaseConfigured){showOnly("config");return}try{const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getDatabase(app);onAuthStateChanged(auth,u=>currentUser=u||null);await signInAnonymously(auth);currentUser=auth.currentUser;showOnly("setup")}catch(e){console.error(e);configView.innerHTML=`<div class="section-title"><h2>⚠️ Firebase non è raggiungibile</h2></div><p>${esc(e.message||"Errore di configurazione")}</p><p>Controlla <strong>firebase-config.js</strong>, l'Autenticazione anonima e il Realtime Database.</p>`;showOnly("config")}}
init();
